### ISSUE TITLE
Bulk upload, GPX file causes ERROR: Exception in ASGI application

### ISSUE THREAD

**Issue by gennit** [joaovitoriasilva/endurain#25]
All file exported from Strava, directory is 1860 total files from the activities folder from Strava export.

Full log:

INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
Backend startup event
INFO:     192.168.1.41:53742 - "OPTIONS /users/number HTTP/1.1" 200 OK
INFO:     192.168.1.41:53741 - "OPTIONS /users/all/page_number/1/num_records/5 HTTP/1.1" 200 OK
INFO:     192.168.1.41:53740 - "GET /user_images/2.jpeg HTTP/1.1" 200 OK
INFO:     192.168.1.41:53743 - "GET /users/number HTTP/1.1" 200 OK
INFO:     192.168.1.41:53744 - "GET /users/all/page_number/1/num_records/5 HTTP/1.1" 200 OK
INFO:     192.168.1.41:53750 - "POST /activities/create/bulkimport HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/activities/utils.py", line 81, in parse_file
    parsed_info = gpx_utils.parse_gpx_file(filename, token_user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/gpx/utils.py", line 132, in parse_gpx_file
    city = location_data["city"]
           ~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/activities/utils.py", line 37, in parse_and_store_activity_from_file
    parsed_info = parse_file(token_user_id, file_extension, file_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/activities/utils.py", line 98, in parse_file
    raise HTTPException(
fastapi.exceptions.HTTPException: 500: Internal Server Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 162, in __call__
    await self.background()
  File "/usr/local/lib/python3.12/site-packages/starlette/background.py", line 45, in __call__
    await task()
  File "/usr/local/lib/python3.12/site-packages/starlette/background.py", line 28, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/app/activities/utils.py", line 49, in parse_and_store_activity_from_file
    raise HTTPException(
fastapi.exceptions.HTTPException: 500: Internal Server Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 631, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 68, in wrapped_app
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.

**Comment by joaovitoriasilva** [comment]
Hello, thanks for reaching out.

I did my testing with .gpx files exported from Strava, so the issue should not be the Strava output.
Do you have the GEOCODES_MAPS_API variable configured like stated in the README file?

The issue appears to be related to the field "city" being null.

**Comment by gennit** [comment]
Hi, appreciate the response.  Yes certainly do have the API key defined in the docker compose.  Should the city field in the gpx file?

**Comment by joaovitoriasilva** [comment]
The city is calculated based on the first track point. It uses the  lat/long pair and queries the geocodes api for the location, that includes the city.

Is there any chance you can share with me the .gox file that is causing the issue for me to test locally?

Thank you

**Comment by gennit** [comment]
Happy to, is there any way to tell which file it is?  There are 2000+ files in that folder at the moment.

**Comment by joaovitoriasilva** [comment]
There is a new build for both images "dev_06092024" that logs the file that is being processed. If you use it instead of the "latest" one you will be able to see which one is causing this.

**Comment by gennit** [comment]
[11004031278.zip](https://github.com/user-attachments/files/16920962/11004031278.zip)
Attached.

**Comment by joaovitoriasilva** [comment]
Hi @gennit I can't reproduce the error in my environment with the GEOCODES_MAPS_API set. Please see details below.

No errors:
<img width="866" alt="Screenshot 2024-09-10 at 15 30 20" src="https://github.com/user-attachments/assets/0c1ae9f6-cef0-4052-83f7-e67c6580f7d5">

Activity is created with success:
![Screenshot 2024-09-10 at 15 31 31](https://github.com/user-attachments/assets/c86f38bc-93c2-49c8-9de1-613b7f55ff37)

However I removed my GEOCODES_MAPS_API variable from the docker compose file in order to simulate that this was not provided or was incorrect and I get the error you report. So I believe something is wrong with your GEOCODES_MAPS_API setting.

I will however try to mitigate the error from happening in the future.

**Comment by gennit** [comment]
I have checked my API key and still looks valid - I wonder if this is a limitation of the number of API calls / second being there are so many files being imported?

**Comment by joaovitoriasilva** [comment]
Maybe. I believe GEOCODES free tier allows 1 request per second, so it can be.
I just pushed a new dev version "dev_11092024". It should log the specific error. Can you check please?

Thanks.

**Comment by gennit** [comment]
I think we have our answer

```
Processing file: bulk_import/2225405324.gpx
Processing file: bulk_import/3474034180.gpx
Processing file: bulk_import/6208087793.gpx
Processing file: bulk_import/2404893700.gpx
Processing file: bulk_import/9310570324.gpx
Processing file: bulk_import/11004031278.gpx
INFO:     192.168.1.218:59033 - "POST /activities/create/bulkimport HTTP/1.1" 200 OK
Parsing file:  bulk_import/9005639437.gpx
Parsing file:  bulk_import/5482218964.gpx
Error in location_based_on_coordinates - 429 Client Error: Too Many Requests for url: https://geocode.maps.co/reverse?lat=-27.312872&lon=153.009805&api_key=66d169d29de64840272283oai09557a
Parsing file:  bulk_import/2290574901.gpx
Parsing file:  bulk_import/8709838746.gpx
Error in location_based_on_coordinates - 429 Client Error: Too Many Requests for url: https://geocode.maps.co/reverse?lat=-27.312889&lon=153.009474&api_key=66d169d29de64840272283oai09557a
Parsing file:  bulk_import/2518818834.gpx
Parsing file:  bulk_import/12098862996.gpx
Error in location_based_on_coordinates - 429 Client Error: Too Many Requests for url: https://geocode.maps.co/reverse?lat=-27.312798&lon=153.009573&api_key=66d169d29de64840272283oai09557a
Parsing file:  bulk_import/9054601691.gpx
```

**Comment by joaovitoriasilva** [comment]
Ok, good to know. The crappy logging was the problem here. :D 
Just to confirm, the files that were processed with success were deleted from the filesystem, and the ones that were not, are still there correct?

If you click the bulk import action again, it should import some more?

**Comment by gennit** [comment]
Definitely seems to be processing and deleting, I'm currently re-running it to hope to get to zero files.  Will let you know.  Wasn't aware it deletes as it goes, so that's helpful to understand.

**Comment by gennit** [comment]
Got it down to 57 files to go, but the process seems to have stopped, now even re-running it, no files are removed and there are no interesting logs (using provided dev build)
```
INFO:     192.168.1.218:64441 - "OPTIONS /activities/create/bulkimport HTTP/1.1" 200 OK
Processing file: bulk_import/10652573072.fit
Processing file: bulk_import/10632721962.fit
Processing file: bulk_import/4507981276.fit
Processing file: bulk_import/4463273928.fit
Processing file: bulk_import/4424196083.fit
Processing file: bulk_import/10626105516.fit
Processing file: bulk_import/4978240796.fit
Processing file: bulk_import/6323068239.gpx
Processing file: bulk_import/4302830112.fit
Processing file: bulk_import/4440507830.fit
Processing file: bulk_import/2018326982.fit
Processing file: bulk_import/4266556909.fit
Processing file: bulk_import/10678954808.fit
Processing file: bulk_import/4704408712.fit
Processing file: bulk_import/4607646653.fit
Processing file: bulk_import/4530797466.fit
Processing file: bulk_import/4424194907.fit
Processing file: bulk_import/10427949729.gpx
Processing file: bulk_import/4266557480.fit
Processing file: bulk_import/10673062933.fit
Processing file: bulk_import/4540044461.fit
Processing file: bulk_import/2048176287.fit
Processing file: bulk_import/4246071812.gpx
Processing file: bulk_import/4302829670.fit
Processing file: bulk_import/10692677401.fit
Processing file: bulk_import/2012008431.fit
Processing file: bulk_import/2028993230.fit
Processing file: bulk_import/10639337120.fit
Processing file: bulk_import/2046167031.fit
Processing file: bulk_import/1927367469.gpx
Processing file: bulk_import/4440508218.fit
Processing file: bulk_import/4424195125.fit
Processing file: bulk_import/2040097259.fit
Processing file: bulk_import/2026880341.fit
Processing file: bulk_import/7081771053.fit
Processing file: bulk_import/10646050676.fit
Processing file: bulk_import/2044005998.fit
Processing file: bulk_import/2033229553.fit
Processing file: bulk_import/2025095710.fit
Processing file: bulk_import/2041975036.fit
Processing file: bulk_import/2016379057.fit
Processing file: bulk_import/4571490550.fit
Processing file: bulk_import/10424365086.gpx
Processing file: bulk_import/4424199746.fit
Processing file: bulk_import/4468073751.fit
Processing file: bulk_import/1925401266.gpx
Processing file: bulk_import/2031250495.fit
Processing file: bulk_import/4446689648.fit
Processing file: bulk_import/4703030856.fit
Processing file: bulk_import/2012426937.fit
Processing file: bulk_import/2014136600.fit
Processing file: bulk_import/2054962320.fit
Processing file: bulk_import/10686005190.fit
Processing file: bulk_import/4424194745.fit
INFO:     192.168.1.218:64445 - "POST /activities/create/bulkimport HTTP/1.1" 200 OK
```

**Comment by joaovitoriasilva** [comment]
Can you try to upload one of them manually and see if an error is displayed?

Thanks.

**Comment by gennit** [comment]
Not sure it is that useful but:
Parsing file:  uploads/10424365086.gpx
INFO:     192.168.1.218:53676 - "POST /activities/create/upload HTTP/1.1" 500 Internal Server Error

File attached for reference.

[10424365086.zip](https://github.com/user-attachments/files/17000693/10424365086.zip)

**Comment by joaovitoriasilva** [comment]
Hi again. So that specific file is not importing because it is not valid. It is an empty GPX file with no track points data. See attached photo.

<img width="773" alt="Screenshot 2024-09-16 at 22 35 43" src="https://github.com/user-attachments/assets/259d17ce-1c2b-4c9f-807e-e272c7691d2e">
