### ISSUE TITLE
Garmin Connect Internal Server error - Assertion Error?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [joaovitoriasilva/endurain#54]
Hi, I've attached the logs below but there's some kind of Internal Server Error coming up when I'm trying to reconnect my Garmin Connect. Is this on the Garmin side, or Endurain side of things?

```
endurain_backend  | 2024-11-26T14:01:40.630841078Z INFO:     192.168.1.170:43000 - "POST /api/v1/garminconnect/link HTTP/1.1" 500 Internal Server Error
endurain_backend  | 2024-11-26T14:01:40.631812293Z ERROR:    Exception in ASGI application
endurain_backend  | 2024-11-26T14:01:40.631820095Z Traceback (most recent call last):
endurain_backend  | 2024-11-26T14:01:40.631821565Z   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
endurain_backend  | 2024-11-26T14:01:40.631822943Z     result = await app(  # type: ignore[func-returns-value]
endurain_backend  | 2024-11-26T14:01:40.631823999Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631825020Z   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
endurain_backend  | 2024-11-26T14:01:40.631826155Z     return await self.app(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631827151Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631828148Z   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
endurain_backend  | 2024-11-26T14:01:40.631829272Z     await super().__call__(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631830449Z   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
endurain_backend  | 2024-11-26T14:01:40.631831526Z     await self.middleware_stack(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631832529Z   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
endurain_backend  | 2024-11-26T14:01:40.631833622Z     raise exc
endurain_backend  | 2024-11-26T14:01:40.631842817Z   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
endurain_backend  | 2024-11-26T14:01:40.631843759Z     await self.app(scope, receive, _send)
endurain_backend  | 2024-11-26T14:01:40.631844522Z   File "/usr/local/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 743, in __call__
endurain_backend  | 2024-11-26T14:01:40.631845395Z     await self.app(scope, otel_receive, otel_send)
endurain_backend  | 2024-11-26T14:01:40.631846157Z   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__
endurain_backend  | 2024-11-26T14:01:40.631847007Z     await self.simple_response(scope, receive, send, request_headers=headers)
endurain_backend  | 2024-11-26T14:01:40.631847813Z   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response
endurain_backend  | 2024-11-26T14:01:40.631848682Z     await self.app(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631849444Z   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
endurain_backend  | 2024-11-26T14:01:40.631850286Z     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631851061Z   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
endurain_backend  | 2024-11-26T14:01:40.631851911Z     raise exc
endurain_backend  | 2024-11-26T14:01:40.631852617Z   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
endurain_backend  | 2024-11-26T14:01:40.631853456Z     await app(scope, receive, sender)
endurain_backend  | 2024-11-26T14:01:40.631854465Z   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
endurain_backend  | 2024-11-26T14:01:40.631855385Z     await self.middleware_stack(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631856166Z   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
endurain_backend  | 2024-11-26T14:01:40.631857036Z     await route.handle(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631857807Z   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
endurain_backend  | 2024-11-26T14:01:40.631858663Z     await self.app(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631859406Z   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
endurain_backend  | 2024-11-26T14:01:40.631860271Z     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
endurain_backend  | 2024-11-26T14:01:40.631861074Z   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
endurain_backend  | 2024-11-26T14:01:40.631861915Z     raise exc
endurain_backend  | 2024-11-26T14:01:40.631862611Z   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
endurain_backend  | 2024-11-26T14:01:40.631863462Z     await app(scope, receive, sender)
endurain_backend  | 2024-11-26T14:01:40.631864208Z   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
endurain_backend  | 2024-11-26T14:01:40.631865075Z     response = await f(request)
endurain_backend  | 2024-11-26T14:01:40.631867010Z                ^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631867836Z   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
endurain_backend  | 2024-11-26T14:01:40.631868672Z     raw_response = await run_endpoint_function(
endurain_backend  | 2024-11-26T14:01:40.631869448Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631870242Z   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
endurain_backend  | 2024-11-26T14:01:40.631871162Z     return await dependant.call(**values)
endurain_backend  | 2024-11-26T14:01:40.631871903Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631872665Z   File "/app/garmin/router.py", line 46, in garminconnect_link
endurain_backend  | 2024-11-26T14:01:40.631873492Z     await garmin_utils.link_garminconnect(
endurain_backend  | 2024-11-26T14:01:40.631874241Z   File "/app/garmin/utils.py", line 98, in link_garminconnect
endurain_backend  | 2024-11-26T14:01:40.631875191Z     garmin = await asyncio.to_thread(blocking_login)
endurain_backend  | 2024-11-26T14:01:40.631875964Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631876941Z   File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
endurain_backend  | 2024-11-26T14:01:40.631877780Z     return await loop.run_in_executor(None, func_call)
endurain_backend  | 2024-11-26T14:01:40.631878563Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631879368Z   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
endurain_backend  | 2024-11-26T14:01:40.631880214Z     result = self.fn(*self.args, **self.kwargs)
endurain_backend  | 2024-11-26T14:01:40.631880965Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631883869Z   File "/app/garmin/utils.py", line 87, in blocking_login
endurain_backend  | 2024-11-26T14:01:40.631884707Z     garmin.login()
endurain_backend  | 2024-11-26T14:01:40.631885587Z   File "/usr/local/lib/python3.12/site-packages/garminconnect/__init__.py", line 212, in login
endurain_backend  | 2024-11-26T14:01:40.631886475Z     self.display_name = self.garth.profile["displayName"]
endurain_backend  | 2024-11-26T14:01:40.631887312Z                         ^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631888093Z   File "/usr/local/lib/python3.12/site-packages/garth/http.py", line 104, in profile
endurain_backend  | 2024-11-26T14:01:40.631888937Z     assert isinstance(self._profile, dict)
endurain_backend  | 2024-11-26T14:01:40.631889689Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
endurain_backend  | 2024-11-26T14:01:40.631890460Z AssertionError
```

**Comment by joaovitoriasilva** [comment]
Hello. This should be fixed in v0.6.5. I will close the issue, but if the issue persists please feel free to open it again.

Thank you.

**Comment by gardiol** [comment]
I am seeing the same issue on 0.11.2?

**Comment by gardiol** [comment]
I am running on container, and the output of the suggested update command above is:
```
/app/backend # pip install --upgrade garminconnect
Requirement already satisfied: garminconnect in /usr/local/lib/python3.13/site-packages (0.2.26)
Requirement already satisfied: garth==0.5.3 in /usr/local/lib/python3.13/site-packages (from garminconnect) (0.5.3)
Requirement already satisfied: pydantic<3.0.0,>=1.10.12 in /usr/local/lib/python3.13/site-packages (from garth==0.5.3->garminconnect) (2.11.4)
Requirement already satisfied: requests-oauthlib<3.0.0,>=1.3.1 in /usr/local/lib/python3.13/site-packages (from garth==0.5.3->garminconnect) (2.0.0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.13/site-packages (from garth==0.5.3->garminconnect) (2.32.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/site-packages (from pydantic<3.0.0,>=1.10.12->garth==0.5.3->garminconnect) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.13/site-packages (from pydantic<3.0.0,>=1.10.12->garth==0.5.3->garminconnect) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.13/site-packages (from pydantic<3.0.0,>=1.10.12->garth==0.5.3->garminconnect) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.13/site-packages (from pydantic<3.0.0,>=1.10.12->garth==0.5.3->garminconnect) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.13/site-packages (from requests<3.0.0,>=2.0.0->garth==0.5.3->garminconnect) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/site-packages (from requests<3.0.0,>=2.0.0->garth==0.5.3->garminconnect) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/site-packages (from requests<3.0.0,>=2.0.0->garth==0.5.3->garminconnect) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/site-packages (from requests<3.0.0,>=2.0.0->garth==0.5.3->garminconnect) (2025.4.26)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.13/site-packages (from requests-oauthlib<3.0.0,>=1.3.1->garth==0.5.3->garminconnect) (3.2.2)
```

The actual trace log is:

```
[endurain] | INFO:     10.89.0.5:51076 - "POST /api/v1/garminconnect/link HTTP/1.0" 500 Internal Server Error                                                                                
[endurain] | ERROR:    Exception in ASGI application                                                                                                                                         
[endurain] |   + Exception Group Traceback (most recent call last):                                                                                                                          
[endurain] |   |   File "/usr/local/lib/python3.13/site-packages/starlette/_utils.py", line 76, in collapse_excgroups                                                                        
[endurain] |   |     yield                                                                                                                                                                   
[endurain] |   |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 177, in __call__                                                                        
[endurain] |   |     async with anyio.create_task_group() as task_group:                                                                                                                     
[endurain] |   |                ~~~~~~~~~~~~~~~~~~~~~~~^^                                                                                                                                    
[endurain] |   |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__                                                                        
[endurain] |   |     raise BaseExceptionGroup(                                                                                                                                               
[endurain] |   |         "unhandled errors in a TaskGroup", self._exceptions                                                                                                                 
[endurain] |   |     ) from None                                                                                                                                                             
[endurain] |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)                                                                                                           
[endurain] |   +-+---------------- 1 ----------------                                                                                                                                        
[endurain] |     | Traceback (most recent call last):                                                                                                                                        
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi                                                                
[endurain] |     |     result = await app(  # type: ignore[func-returns-value]                                                                                                               
[endurain] |     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                               
[endurain] |     |         self.scope, self.receive, self.send                                                                                                                               
[endurain] |     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                               
[endurain] |     |     )                                                                                                                                                                     
[endurain] |     |     ^                                                                                                                                                                     
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__                                                                
[endurain] |     |     return await self.app(scope, receive, send)                                                                                                                           
[endurain] |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                           
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__                                                                          
[endurain] |     |     await super().__call__(scope, receive, send)                                                                                                                          
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 112, in __call__                                                                         
[endurain] |     |     await self.middleware_stack(scope, receive, send)                                                                                                                     [endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__   
[endurain] |     |     raise exc                                                                                                                                          10:32:38 [359/1970]
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
[endurain] |     |     await self.app(scope, receive, _send)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 743, in __call__
[endurain] |     |     await self.app(scope, otel_receive, otel_send)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 176, in __call__
[endurain] |     |     with recv_stream, send_stream, collapse_excgroups():
[endurain] |     |                                    ~~~~~~~~~~~~~~~~~~^^
[endurain] |     |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
[endurain] |     |     self.gen.throw(value)
[endurain] |     |     ~~~~~~~~~~~~~~^^^^^^^
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
[endurain] |     |     raise exc
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 178, in __call__
[endurain] |     |     response = await self.dispatch_func(request, call_next)
[endurain] |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |     |   File "/app/backend/session/schema.py", line 62, in dispatch
[endurain] |     |     response = await call_next(request)
[endurain] |     |                ^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 156, in call_next
[endurain] |     |     raise app_exc
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 141, in coro
[endurain] |     |     await self.app(scope, receive_or_disconnect, send_no_error)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/cors.py", line 93, in __call__
[endurain] |     |     await self.simple_response(scope, receive, send, request_headers=headers)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/cors.py", line 144, in simple_response
[endurain] |     |     await self.app(scope, receive, send)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
[endurain] |     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[endurain] |     |     raise exc
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
[endurain] |     |     await app(scope, receive, sender)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 714, in __call__
[endurain] |     |     await self.middleware_stack(scope, receive, send)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 734, in app
[endurain] |     |     await route.handle(scope, receive, send)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
[endurain] |     |     await self.app(scope, receive, send)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
[endurain] |     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[endurain] |     |     raise exc
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
[endurain] |     |     await app(scope, receive, sender)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 73, in app
[endurain] |     |     response = await f(request)
[endurain] |     |                ~~~~~~~~~~~~~~^^                                                                                                                        10:32:38 [309/1970]
[endurain] |     |   File "/usr/local/lib/python3.13/contextlib.py", line 768, in __aexit__
[endurain] |     |     raise exc
[endurain] |     |   File "/usr/local/lib/python3.13/contextlib.py", line 751, in __aexit__
[endurain] |     |     cb_suppress = await cb(*exc_details)
[endurain] |     |                   ^^^^^^^^^^^^^^^^^^^^^^
[endurain] |     |   File "/usr/local/lib/python3.13/contextlib.py", line 235, in __aexit__
[endurain] |     |     await self.gen.athrow(value)
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/fastapi/concurrency.py", line 30, in contextmanager_in_threadpool
[endurain] |     |     await anyio.to_thread.run_sync(
[endurain] |     |         cm.__exit__, type(e), e, e.__traceback__, limiter=exit_limiter
[endurain] |     |     )
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/anyio/to_thread.py", line 56, in run_sync
[endurain] |     |     return await get_async_backend().run_sync_in_worker_thread(
[endurain] |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |     |         func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
[endurain] |     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |     |     )
[endurain] |     |     ^
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
[endurain] |     |     return await future
[endurain] |     |            ^^^^^^^^^^^^
[endurain] |     |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 967, in run
[endurain] |     |     result = context.run(func, *args)
[endurain] |     |   File "/usr/local/lib/python3.13/contextlib.py", line 195, in __exit__
[endurain] |     |     exc.__traceback__ = traceback
[endurain] |     |     ^^^^^^^^^^^^^^^^^
[endurain] |     |   File "<string>", line 16, in __setattr__
[endurain] |     | dataclasses.FrozenInstanceError: cannot assign to field '__traceback__'
[endurain] |     +------------------------------------
[endurain] | 
[endurain] | During handling of the above exception, another exception occurred:
[endurain] | 
[endurain] | Traceback (most recent call last):
[endurain] |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
[endurain] |     result = await app(  # type: ignore[func-returns-value]
[endurain] |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |         self.scope, self.receive, self.send
[endurain] |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |     )
[endurain] |     ^
[endurain] |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
[endurain] |     return await self.app(scope, receive, send)
[endurain] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
[endurain] |     await super().__call__(scope, receive, send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 112, in __call__
[endurain] |     await self.middleware_stack(scope, receive, send)                                                                                                        10:32:38 [262/1970]
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__
[endurain] |     raise exc
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
[endurain] |     await self.app(scope, receive, _send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 743, in __call__
[endurain] |     await self.app(scope, otel_receive, otel_send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 176, in __call__
[endurain] |     with recv_stream, send_stream, collapse_excgroups():
[endurain] |                                    ~~~~~~~~~~~~~~~~~~^^
[endurain] |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
[endurain] |     self.gen.throw(value)
[endurain] |     ~~~~~~~~~~~~~~^^^^^^^
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
[endurain] |     raise exc
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 178, in __call__
[endurain] |     response = await self.dispatch_func(request, call_next)
[endurain] |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |   File "/app/backend/session/schema.py", line 62, in dispatch
[endurain] |     response = await call_next(request)
[endurain] |                ^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 156, in call_next
[endurain] |     raise app_exc
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/base.py", line 141, in coro
[endurain] |     await self.app(scope, receive_or_disconnect, send_no_error)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/cors.py", line 93, in __call__
[endurain] |     await self.simple_response(scope, receive, send, request_headers=headers)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/cors.py", line 144, in simple_response
[endurain] |     await self.app(scope, receive, send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
[endurain] |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[endurain] |     raise exc
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
[endurain] |     await app(scope, receive, sender)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 714, in __call__
[endurain] |     await self.middleware_stack(scope, receive, send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 734, in app
[endurain] |     await route.handle(scope, receive, send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
[endurain] |     await self.app(scope, receive, send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
[endurain] |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[endurain] |     raise exc
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
[endurain] |     await app(scope, receive, sender)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 73, in app                                                                       10:39:34 [215/1970]
[endurain] |     response = await f(request)
[endurain] |                ^^^^^^^^^^^^^^^^
[endurain] |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 290, in app
[endurain] |     async with AsyncExitStack() as async_exit_stack:
[endurain] |                ~~~~~~~~~~~~~~^^
[endurain] |   File "/usr/local/lib/python3.13/contextlib.py", line 768, in __aexit__
[endurain] |     raise exc
[endurain] |   File "/usr/local/lib/python3.13/contextlib.py", line 751, in __aexit__
[endurain] |     cb_suppress = await cb(*exc_details)
[endurain] |                   ^^^^^^^^^^^^^^^^^^^^^^
[endurain] |   File "/usr/local/lib/python3.13/contextlib.py", line 235, in __aexit__
[endurain] |     await self.gen.athrow(value)
[endurain] |   File "/usr/local/lib/python3.13/site-packages/fastapi/concurrency.py", line 30, in contextmanager_in_threadpool
[endurain] |     await anyio.to_thread.run_sync(
[endurain] |         cm.__exit__, type(e), e, e.__traceback__, limiter=exit_limiter
[endurain] |     )
[endurain] |   File "/usr/local/lib/python3.13/site-packages/anyio/to_thread.py", line 56, in run_sync
[endurain] |     return await get_async_backend().run_sync_in_worker_thread(
[endurain] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |         func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
[endurain] |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[endurain] |     )
[endurain] |     ^
[endurain] |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
[endurain] |     return await future
[endurain] |            ^^^^^^^^^^^^
[endurain] |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 967, in run
[endurain] |     result = context.run(func, *args)
[endurain] |   File "/usr/local/lib/python3.13/contextlib.py", line 195, in __exit__
[endurain] |     exc.__traceback__ = traceback
[endurain] |     ^^^^^^^^^^^^^^^^^
[endurain] |   File "<string>", line 16, in __setattr__
[endurain] | dataclasses.FrozenInstanceError: cannot assign to field '__traceback__'
```

**Comment by gardiol** [comment]
Update: it was somehow bad credentials... i will open a new ticket requesting a proper error message :)
